name: Go Pipeline

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: trapajim/go-pipeline-action@v1
        with:
          go-version: '1.21.6'
          golangci-run: true
